version: '3.8'

services:
  bot:
    build: .
    image: ghcr.io/tkaixiang/storeman-bot:latest
    restart: unless-stopped
    depends_on: 
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/
    ports: 
      - "80:80"
    secrets:
      - source: dotenv
        target: /app/.env

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

secrets:
  dotenv: 
    file: ./.env
